# Generated by Django 4.2.5 on 2023-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_is_funcionario_usuario_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('semestres', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='autor',
            name='data_falecimento',
        ),
    ]
