version: '3'

services:
  bibliotech-front:
    container_name: BiblioTech-Front 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - "/app/node_modules"
    ports:
      - "3000:3000"
    env_file:
      - .env
