# Generated by Django 4.2.5 on 2023-09-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_funcionario',
            new_name='professor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='aluno',
            field=models.BooleanField(default=False),
        ),
    ]
