# Generated by Django 4.2.5 on 2023-09-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_curso_remove_autor_data_falecimento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicadora',
            new_name='Editora',
        ),
        migrations.RenameField(
            model_name='detalheslivro',
            old_name='publicadora',
            new_name='editora',
        ),
    ]
