# Generated by Django 4.2.6 on 2023-10-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_publicadora_editora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('ra', models.CharField(max_length=100, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('professor', models.BooleanField(default=False)),
                ('aluno', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.aluno'),
        ),
    ]
