# Generated by Django 4.2.6 on 2023-10-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_aluno_remove_emprestimo_usuario_delete_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='professor',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.curso'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.aluno'),
        ),
    ]
