# Generated by Django 4.2.6 on 2023-10-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_aluno_aluno_remove_aluno_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.aluno')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.autor')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.curso')),
                ('detalhesLivro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.detalheslivro')),
                ('devolucao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.devolucao')),
                ('editora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.editora')),
                ('emprestimo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.emprestimo')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.generolivro')),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.livro')),
            ],
        ),
    ]
